RUN pacman --noconfirm -S dtc python-setuptools autoconf-archive help2man xorg-input xorg-server

RUN mkdir /opt/libgpiod
WORKDIR /opt/libgpiod
RUN curl https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=libgpiod > PKGBUILD
RUN chown -R alarm:alarm .
RUN sudo -u alarm makepkg
RUN pacman -U *.pkg.tar.xz --noconfirm

RUN mkdir /opt/hyperpixel4
RUN git clone https://github.com/pimoroni/hyperpixel4 -b pi3 /opt/hyperpixel4
WORKDIR /opt/hyperpixel4
RUN /bin/bash install.sh
